version: '3'

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: noble6/yamdb_final:latest
    restart: always
    volumes:
      - static-data:/code/static/
      - media-data:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.18.0
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static-data:/code/static/
      - media-data:/code/media/
    depends_on:
      - web

volumes:
  postgres_data:
    driver: local
  static-data:
    driver: local
  media-data:
    driver: local